/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.pizzaria.tela;

import javax.swing.JOptionPane;

/**
 *
 * @author marty
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        pizzaIcone = new javax.swing.JLabel();
        pizzaIcone1 = new javax.swing.JLabel();
        cadastroCliente = new javax.swing.JLabel();
        pesquisarCliente = new javax.swing.JLabel();
        cadastroPedido = new javax.swing.JLabel();
        pesquisaPedido = new javax.swing.JLabel();
        sairSistema = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        operacaoCliente = new javax.swing.JMenu();
        cadCliente = new javax.swing.JMenuItem();
        pesCliente = new javax.swing.JMenuItem();
        sair = new javax.swing.JMenu();
        sistema = new javax.swing.JMenuItem();
        deslogar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Sistema Pizzaria Topzera");

        pizzaIcone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/contato/imagem/Pizza-icon_30282 (1).png"))); // NOI18N

        pizzaIcone1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/contato/imagem/Pizza-icon_30282 (1).png"))); // NOI18N

        cadastroCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/contato/imagem/cadastroCliente.png"))); // NOI18N
        cadastroCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cadastroCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cadastroCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastroClienteMouseClicked(evt);
            }
        });

        pesquisarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/contato/imagem/pesquisaCliente.png"))); // NOI18N
        pesquisarCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pesquisarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pesquisarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pesquisarClienteMouseClicked(evt);
            }
        });

        cadastroPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/contato/imagem/pedidoPizza.png"))); // NOI18N
        cadastroPedido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cadastroPedido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cadastroPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastroPedidoMouseClicked(evt);
            }
        });

        pesquisaPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/contato/imagem/pessquisaPizza.png"))); // NOI18N
        pesquisaPedido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pesquisaPedido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pesquisaPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pesquisaPedidoMouseClicked(evt);
            }
        });

        sairSistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/contato/imagem/sair.png"))); // NOI18N
        sairSistema.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sairSistema.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sairSistema.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sairSistemaMouseClicked(evt);
            }
        });

        operacaoCliente.setText("Cliente");
        operacaoCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        cadCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        cadCliente.setText("Cadastrar");
        cadCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadClienteActionPerformed(evt);
            }
        });
        operacaoCliente.add(cadCliente);
        cadCliente.getAccessibleContext().setAccessibleDescription("Cadastrar Cliente");

        pesCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        pesCliente.setText("Pesquisar");
        pesCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pesCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesClienteActionPerformed(evt);
            }
        });
        operacaoCliente.add(pesCliente);
        pesCliente.getAccessibleContext().setAccessibleDescription("Pesquisar Cliente");

        jMenuBar1.add(operacaoCliente);
        operacaoCliente.getAccessibleContext().setAccessibleDescription("Opcões Cliente");

        sair.setText("Sair");
        sair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sair.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sairMouseClicked(evt);
            }
        });

        sistema.setText("Sair Do Sistema");
        sistema.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sistema.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sistemaMouseClicked(evt);
            }
        });
        sistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sistemaActionPerformed(evt);
            }
        });
        sair.add(sistema);

        deslogar.setText("Desconectar Usuario");
        deslogar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deslogar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deslogarMouseClicked(evt);
            }
        });
        deslogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deslogarActionPerformed(evt);
            }
        });
        sair.add(deslogar);

        jMenuBar1.add(sair);
        sair.getAccessibleContext().setAccessibleDescription("Sair");

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(143, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(pizzaIcone1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(titulo)
                        .addGap(18, 18, 18)
                        .addComponent(pizzaIcone, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(179, 179, 179))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cadastroCliente)
                        .addGap(39, 39, 39)
                        .addComponent(pesquisarCliente)
                        .addGap(33, 33, 33)
                        .addComponent(cadastroPedido)
                        .addGap(37, 37, 37)
                        .addComponent(pesquisaPedido)
                        .addGap(32, 32, 32)
                        .addComponent(sairSistema)
                        .addGap(142, 142, 142))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pizzaIcone1)
                    .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pizzaIcone))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cadastroCliente)
                    .addComponent(pesquisarCliente)
                    .addComponent(cadastroPedido)
                    .addComponent(pesquisaPedido)
                    .addComponent(sairSistema))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        pizzaIcone.getAccessibleContext().setAccessibleDescription("Icone Pizza");
        cadastroCliente.getAccessibleContext().setAccessibleName("Cadastrar Cliente");
        cadastroCliente.getAccessibleContext().setAccessibleDescription("Cadastrar Cliente");
        pesquisarCliente.getAccessibleContext().setAccessibleName("Pesquisar Cliente");
        pesquisarCliente.getAccessibleContext().setAccessibleDescription("Pesquisar Cliente");
        cadastroPedido.getAccessibleContext().setAccessibleName("Cadastrar Pedido");
        cadastroPedido.getAccessibleContext().setAccessibleDescription("Cadastrar Pedido");
        pesquisaPedido.getAccessibleContext().setAccessibleName("Pesquisar Pedido");
        pesquisaPedido.getAccessibleContext().setAccessibleDescription("Pesquisar Pedido");
        sairSistema.getAccessibleContext().setAccessibleName("Sair");
        sairSistema.getAccessibleContext().setAccessibleDescription("Sair");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadClienteActionPerformed
        new CadastroCliente().setVisible(true);
    }//GEN-LAST:event_cadClienteActionPerformed

    private void pesClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesClienteActionPerformed
        new PesquisaCliente().setVisible(true);
    }//GEN-LAST:event_pesClienteActionPerformed

    private void sairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairMouseClicked

    }//GEN-LAST:event_sairMouseClicked

    private void cadastroClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastroClienteMouseClicked
        new CadastroCliente().setVisible(true);
    }//GEN-LAST:event_cadastroClienteMouseClicked

    private void pesquisarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pesquisarClienteMouseClicked
        new PesquisaCliente().setVisible(true);
    }//GEN-LAST:event_pesquisarClienteMouseClicked

    private void sairSistemaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairSistemaMouseClicked
        int opcao = JOptionPane.showConfirmDialog(null,
                "Você tem certeza que deseja sair?");
        if (opcao == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_sairSistemaMouseClicked

    private void sistemaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sistemaMouseClicked

    }//GEN-LAST:event_sistemaMouseClicked

    private void deslogarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deslogarMouseClicked

    }//GEN-LAST:event_deslogarMouseClicked

    private void sistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sistemaActionPerformed
        int opcao = JOptionPane.showConfirmDialog(null,
                "Você tem certeza que deseja sair?");
        if (opcao == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_sistemaActionPerformed

    private void deslogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deslogarActionPerformed
        int opcao = JOptionPane.showConfirmDialog(null,
                "Você tem certeza que deseja se desconectar?");
        if (opcao == 0) {
            this.dispose();
            new LoginUsuario().setVisible(true);
        }
    }//GEN-LAST:event_deslogarActionPerformed

    private void cadastroPedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastroPedidoMouseClicked
        new CadastroPedido().setVisible(true);
    }//GEN-LAST:event_cadastroPedidoMouseClicked

    private void pesquisaPedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pesquisaPedidoMouseClicked
        new PesquisarPedido().setVisible(true);
    }//GEN-LAST:event_pesquisaPedidoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cadCliente;
    private javax.swing.JLabel cadastroCliente;
    private javax.swing.JLabel cadastroPedido;
    private javax.swing.JMenuItem deslogar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu operacaoCliente;
    private javax.swing.JMenuItem pesCliente;
    private javax.swing.JLabel pesquisaPedido;
    private javax.swing.JLabel pesquisarCliente;
    private javax.swing.JLabel pizzaIcone;
    private javax.swing.JLabel pizzaIcone1;
    private javax.swing.JMenu sair;
    private javax.swing.JLabel sairSistema;
    private javax.swing.JMenuItem sistema;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
